apiVersion: v1
kind: Service
metadata:
  name: aebs-db
  namespace: olavur
spec:
  ports:
    - port: 7474
      targetPort: 7474
      name: 'http-port'
    - port: 7687
      targetPort: 7687
      name: 'bolt-port'
  selector:
    app: aebs-db
